### ISSUE TITLE
scene rotation

### ISSUE THREAD

**Issue by Bin-ze** [vuer-ai/vuer#10]
When I use Vuer to visualize a 3dgs scene and drag the mouse, the scene will rotate around the specified world axis.

before：
<img width="992" alt="image" src="https://github.com/vuer-ai/vuer/assets/72087870/a7502e13-587b-4274-a00d-cbc025c9c52a">
 
after：

<img width="1057" alt="image" src="https://github.com/vuer-ai/vuer/assets/72087870/0206093a-343a-41bf-aa6e-207562b18ccc">

But this will cause the camera to see through the wall in indoor scenes.
I wish I could keep the scene the same and change the camera position.

Therefore I want to know how I can set up the rotation to keep the camera's origin fixed in the camera coordinate system and just change the R matrix of the camera coordinate system. This simulates the effect of humans walking and turning in the scene.

**Comment by geyang** [comment]
woops! @Bin-ze Just saw this message!  Can you share a minimal example (data included), and I can take a look/reproduce the behavior?

**Comment by geyang** [comment]
Hi @Bin-ze, this is currently not supported. We use what is called Orbit Control, which centers around a particular target point.

I am closing this issue, but folks should feel free to bump this up to help with triage.
