### ISSUE TITLE
Black Screen When Entering VR Mode on Meta Quest 3

### ISSUE THREAD

**Issue by AddisionHarry** [vuer-ai/vuer#17]
Firstly, I want to express my sincere gratitude for your outstanding contributions to the open-source community. The Vuer library is a remarkable tool, and your dedication is truly appreciated.

I'm currently using the Vuer library to deploy a VR project on Meta Quest 3. However, I've encountered an issue that I hope you can help me resolve. When accessing the corresponding webpage through the default browser on the device, the images display correctly (I'm currently testing by displaying two solid color images in the left and right eyes).

The problem arises when I click "Enter VR Mode"—the screen on the Quest goes black. Exiting VR mode using the Meta button on the controller shows that the immersive webpage is still running in the background. If I close it and refresh the webpage without entering VR mode again, the images display correctly.

![Before entering VR mode](https://github.com/user-attachments/assets/32b56d8b-9f68-407e-981b-e92a9dbb4fbd)
![After entering VR mode](https://github.com/user-attachments/assets/c782e5b9-af20-42a5-8125-ac6e49534802)
![Exit using the Meta button on the controller](https://github.com/user-attachments/assets/477dd756-a3f0-44fd-ad7b-df4b37e8a648)

I'm unsure if this issue is related to my browser or device settings, or if there might be a problem in the code. I'd greatly appreciate any insights or guidance you could provide.

Thank you once again for your support and contributions. Your work makes a significant difference.

**Comment by lmj250** [comment]
Are you connected through adb? Does Quest 3 need a network to open the Vuer page?

**Comment by AddisionHarry** [comment]
Yes, I was connected through adb and had a stable connection. Later, I found that simply rebooting the device and reconnecting via a different port solved the issue. The problem might have been related to not properly acknowledging Oculus prompts, such as the one asking to enter immersive mode.

Thank you for your help!

**Comment by AddisionHarry** [comment]
Yes, I was connected through adb and had a stable connection. Later, I found that simply rebooting the device and reconnecting via a different port solved the issue. The problem might have been related to not properly acknowledging Oculus prompts, such as the one asking to enter immersive mode.

Thank you for your help!
