### ISSUE TITLE
Fixing aiohttp dependency version

### ISSUE THREAD

**Issue by Mnzs1701** [vuer-ai/vuer#31]
Thank you for your great contribution, however when installing vuer via `pip install vuer[all]` the installed version of aiohttp is `3.10.10` however this version seems to give a blank output (no resulting mesh) in the renderer with the only error appearing in terminal as:
```
Traceback (most recent call last):
File "python3.8/site-packages/aiohttp/web_protocol.py", line 653, in finish_response
    prepare_meth = resp.prepare
AttributeError: 'NoneType' object has no attribute 'prepare'
```
This error does not show up if using `pip install aiohttp==3.10.5` or previous versions. It would be great if the version was fixed to `3.10.5` on installation.

**Comment by geyang** [comment]
Thank you for raising the issue! I have reproduced this and have updated the dependencies to use `aiohttp==3.10.5` for now.
