### ISSUE TITLE
how to get the hand data from vuer's Hand API

### ISSUE THREAD

**Issue by jiqimao-1** [vuer-ai/vuer#32]
Hello,when i run hand_tracking's example:

from vuer import Vuer, VuerSession
from vuer.schemas import Hands
from asyncio import sleep

app = Vuer()

@app.add_handler("HAND_MOVE")
async def handler(event, session):
    print(f"Movement Event: key-{event.key}", event.value)

@app.spawn(start=True)
async def main(session: VuerSession):
    # Important: You need to set the `stream` option to `True` to start
    # streaming the hand movement.
    session.upsert @ Hands(stream=True, key="hands")

    while True:
        await sleep(1)
The terminal always show "event.value",but i can't get the data what i want.
I don't konw how to do.
Please help me,thank you.
The following i don't konw how to use in my python script.
/**
 * Left and right pose are relative to the wrist transformations.
 */
export type HandsData = {
  left?: Float32Array;       // 25 * 16 values.
  right?: Float32Array;      // 25 * 16 values.
  leftState: HandState;
  rightState: HandState;
};

export type HandState = {
  pinch: boolean;
  squeeze: boolean;
  tap: boolean;

  pinchValue: number;
  squeezeValue: number;
  tapValue: number;
}

**Comment by jiqimao-1** [comment]
when i use the vuer==0.0.35,nothing shows on the ternimal

**Comment by geyang** [comment]
@jiqimao-1 you need to add `'` around your command if you are using `zsh`.

Copy the installation script verbatim  from the doc site.
