### ISSUE TITLE
The HAND_MOVE event returns hand joints with a length of 25x3 instead of 25x16.

### ISSUE THREAD

**Issue by pbernhaohs87** [vuer-ai/vuer#35]
@geyang  @RogerQi @jansenw95 @evnkm @hannah-y-gao 

I am using vuer==0.0.32rc7 to obtain hand poses with the following code [(Open-TeleVision):](https://github.com/OpenTeleVision/TeleVision)
```
app = Vuer(host='0.0.0.0', cert=cert_file, key=key_file, queries=dict(grid=False), queue_len=3)
```

```
session.upsert @ Hands(fps=fps, stream=True, key="hands", showLeft=False, showRight=False)
```

```
app.add_handler("HAND_MOVE")(on_hand_move)
```

```   
async def on_hand_move(self, event, session, fps=60):
        try:
            self.left_hand_shared[:] = event.value["leftHand"]
            self.right_hand_shared[:] = event.value["rightHand"]
            self.left_landmarks_shared[:] = np.array(event.value["leftLandmarks"]).flatten()
            self.right_landmarks_shared[:] = np.array(event.value["rightLandmarks"]).flatten()
        except: 
            pass
```

However, the return result of `event.value["rightLandmarks"]` has a length of 25x3, not 25x16.

I tried running the [example](https://docs.vuer.ai/en/v0.0.32-rc27/examples/19_hand_tracking.html#) but got the same result. Could you help solve this issue? Please let me know how I can retrieve hand joint information with rotation, either through an available example or by pointing out the error in my code.

**Comment by geyang** [comment]
Glad that you liked the doc!
