### ISSUE TITLE
Gaze tracking interface

### ISSUE THREAD

**Issue by Nealea123** [vuer-ai/vuer#38]
Hello,
Thank you for your great work!  I've been using Apple VisionPro to run your project. And I noticed that Vuer doesn't seem to have a gaze tracking interface. I wonder if there is a gaze tracking interface for WebXR that can be opened in Vuer.

Also, I‘m concerned that Apple and WebXR don't seem to open up a direct underlying gaze interface for security and privacy reasons. Is it impossible to get the underlying eye tracking information through WebXR?

**Comment by geyang** [comment]
The "transient pointer" is designed to provide webXR limited access to gaze data, only during interactions.

We currently use this to point/grasp and interact with objects. Continuous access to gazes, however, is not possible.
